<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ScrewTweaks.Physics.Tires</AssemblyName>
    <RootNamespace>ScrewTweaks.Physics.Tires</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScrewTweaks.Panel\ScrewTweaks.Panel.csproj" />
  </ItemGroup>

</Project>
